### ISSUE TITLE
Apply for Prototype fund?

### ISSUE THREAD

**Issue by vog** [MichaelKreil/routing.js#1]
Just a quick idea: What about applying this project for the Prototype fund?

* https://prototypefund.de/
* https://secure.pt-dlr.de/pt-conference/conference/Prototype_Fund

(Please note that there are only 2 days left for application.)

The goal would be to make it a fully usable routing service. That is, to provide an Open Source alternative to existing routing software. Benefits: Diversity (alternative routing service), also works offline, and is much faster. First version in JavaScript within the browser, later maybe Qt GUI, Android App or command line tool. Perhaps starting with ICE network and/or Berlin public transport, later with other networks as far as OpenData allows.

Does this make sense to you? Or, is the Prototype fund not the right way to push this project forward?

**Comment by MichaelKreil** [comment]
Hi, sorry, completely missed the message.
No, I can't submit this to the Prototype Fund because I'm on the jury. ;)
